# permissions for end users to edit runs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-editor-role
rules:
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runs/status
  verbs:
  - get
