# permissions for end users to view runs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-viewer-role
rules:
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runs/status
  verbs:
  - get
