# permissions for end users to edit runnerimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerimage-editor-role
rules:
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runnerimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkinsfilerunner.io
  resources:
  - runnerimages/status
  verbs:
  - get
