apiVersion: jenkinsfilerunner.io/v1alpha1
kind: Run
metadata:
  name: run-sample
spec:
  image: quay.io/waveywaves/jfr-test@sha256:f8a21694c193c427a0f3ba98988cacf85e5ce99f57e1847b3d6d96dbfa56d4cc
  jenkinsfile:
    configMapRef: jenkinsfile
  configurationAsCode:
    configMapRef: casc
