apiVersion: jenkinsfilerunner.io/v1alpha1
kind: RunnerImage
metadata:
  name: runnerimage-sample
spec:
  plugins:
    - kubernetes
  to: 
    name: quay.io/waveywaves/jfr-test
    secret: waveywaves-jfr-helper-pull-secret  
