apiVersion: jenkinsfilerunner.io/v1alpha1
kind: Run
metadata:
  name: run-sample
spec:
  image: quay.io/waveywaves/jfr-test:latest
  jenkinsfile:
    configMapRef: jenkinsfile
  configurationAsCode:
    configMapRef: casc
